### PR TITLE
add css tickerHover.

### PR DESCRIPTION
**Pull request by dsuket**
I added tickerHover when cssUsing is true.

### CODE REVIEW

**Comment by jjr2527** [comment]
Works perfectly for me.  Thanks @dsuket !!

**Comment by Tidal-Wave** [comment]
Good to know. We will get this merged in in our next update slated for February.

**Comment by Tidal-Wave** [comment]
Added in 4.2.2

**Comment by usman-des** [comment]
same issue bt work perfectly

**Comment by usman-des** [comment]
i have videos in ticker....is it possible that on ticker hover when it will pause i got to video n video is clickable to desire link

**Pull request closed without merging**
