### PR TITLE
Return working state of the slider (true means that a transition is in progress)

### PR DESCRIPTION
**Pull request by mweimerskirch**
This simplifies controlling the slider from outside.

### CODE REVIEW

**Comment by Tidal-Wave** [comment]
Unless Im missing something, this is already a function. Closing for the moment.

**Comment by Tidal-Wave** [comment]
NOTE: The confusion may have come from the fact that the docs haven't been updated on the website. I currently don't have access to the public site to make updates, but the next update 4.2.4 will contain offline docs in the repo that can be built locally and updated by the community.

**Comment by mweimerskirch** [comment]
Well, I still can't see anything like this in the master branch. There are many lines that call "slider.working" internally, but there is currently no way to check from "outside" if the slider is working.

**Comment by Tidal-Wave** [comment]
https://github.com/stevenwanderski/bxslider-4/blob/master/src/js/jquery.bxslider.js#L1467-L1473

Is this not what you are looking for?

**Comment by mweimerskirch** [comment]
Yes, absolutely. My bad, sorry, I looked in my master branch which wasn't in sync with upstream.

**Comment by Tidal-Wave** [comment]
No problem, I hope to push a big update (4.2.4) today or tomorrow so keep an eye out for that.

**Pull request closed without merging**
