### PR TITLE
Bugfix issue #846

### PR DESCRIPTION
**Pull request by tobiju**
Bugfix for issue #846

### CODE REVIEW

**Comment by alex-moreno** [comment]
this seems to fix the issue, can I ask wha wasn't merged at the end?

**Comment by tobiju** [comment]
I think it was just the order of code executed. But at least this does not
fix the bug in ff. That is the reason why I removed the pull request.
Am 18.01.2016 1:48 nachm. schrieb "Alejandro Moreno" <
notifications@github.com>:

**Comment by alex-moreno** [comment]
um, weird, seems to fix it in Chrome. It is difficult to reproduce though

**Comment by tobiju** [comment]
Yes your are right it fixed the chrome issue if useCss is true. But if you
disable it there is another problem maybe on iphone 4 on swipe.
Am 18.01.2016 3:15 nachm. schrieb "Alejandro Moreno" <
notifications@github.com>:

**Comment by alex-moreno** [comment]
Thank you @tobiju

**Pull request closed without merging**
