### PR TITLE
Slider element in every callback and a new method getSliderElement

### PR DESCRIPTION
**Pull request by hanoii**
It's customary and useful to have the slider object on every callback, in case you want to call further methods or alter the DOM (specific to the current slider) so you don't need special selectors to target each slider that triggered the element.

This is very similar to #519, and also removes what was added on #475 for a better approach. This commits also removes trailing spaces from filenames (a nice coding standard making it easier to contribute).

### CODE REVIEW

**Comment by Tidal-Wave** [comment]
Thanks for the PR. We are doing pushes this week so we will review. We are also implementing some jscs checks and better linting so contributing wi be cleaner and easier.

**Comment by Tidal-Wave** [comment]
I will be making these changes in the 4.2.4 update, but since I have made some changes and these commits are rather dirty I will be adding this in manually. Thanks for your work. Closing the PR. Update coming shortly.

**Comment by hanoii** [comment]
That's great. I wonder while you are at it, I needed to update gulp-less to the latest version otherwise it wasn't compiling on node 0.12, I wonder if you may look into updating that as well?

**Comment by Tidal-Wave** [comment]
The next update actually will abandon the gulp approach in favor of grunt due to poor gulp support for assemble atm, which we are using to provide documentation and demos in the repo. Since I don't have access to the website atm and it's documentation is quickly falling behind I am building it directly into the project so it can be compiled locally.

**Pull request closed without merging**
