### PR TITLE
Update jquery.bxslider.min.js

### PR DESCRIPTION
**Pull request by MaxxSoftware**
Fixed issue when yuicompressor throw an 'invalid property id' error when trying to minify.

### CODE REVIEW

**Comment by sekmenhuseyin** [comment]
sorry, i cant see what you've changed. can you submit uncompressed js file too

**Comment by MaxxSoftware** [comment]
I've changed only compressed file.
there are my changes:
Before 
`s.children.css({float:"horizontal"===s.settings.mode?`
After
`s.children.css({"float":"horizontal"===s.settings.mode?`

**Comment by camerongillette** [comment]
@MaxxSoftware If you only update the compressed file, your changes will be overwritten on the next release build. Please update the src file.

**Comment by sekmenhuseyin** [comment]
we have fixed that long ago. however when we use gulp to compress js, quotation marks disappear.

**Pull request closed without merging**
