### PR TITLE
fix for issues #951, #958

### PR DESCRIPTION
**Pull request by deansimcox**
This is a small fix for issues #951 and #958.
The issue was in the goToSlide method. Basically the method was setting a new active index before an if statement that checks if the slider is currently running. This meant that if a user tried to go to a new slide during a current slide transition, the slider would update its' new active index, reach the this if statement which would equal true, and then end the method with a return.
To the user, it would look like the slider skipped a slide.. because it kind of did.

### CODE REVIEW

**Comment by deansimcox** [comment]
Let me know if there's anything else I can/need to do to get this merged in.

**Comment by donets** [comment]
Please, merge this request ASAP.

**Comment by gabrielkaputa** [comment]
Merging this would be very welcome here also, it's the only thing keeping us from using this awesome slider.

**Comment by borantula** [comment]
thanks! this fixed the issue for me as well. It's sad to see this plugin is ignored by author :(

**Comment by sekmenhuseyin** [comment]
these issues has fixed, thanks for your comments

**Comment by stasyabezruk** [comment]
for me, this issue hasn't been still working

**Pull request closed without merging**
