### PR TITLE
This fixes the responsive issue for horizontal mode for issue #611.

### PR DESCRIPTION
**Pull request by kellykarnetsky**
This fixes the responsive issue for horizontal mode for issue #611 and maybe #487. I haven't tested the last one but the first ticket was referenced in that.

### CODE REVIEW

**Comment by Tidal-Wave** [comment]
Thanks. I'll review this later and let you know if anything needs changing.

**Comment by Tidal-Wave** [comment]
Fixed in 4.1.3

**Comment by Tidal-Wave** [comment]
I reversed this because it was causing the loading-gif not to show during load.

**Comment by kellykarnetsky** [comment]
Ok. I will take a look at it more to find a better solution. Leaving it relative makes it not responsive and that's not good :/

**Comment by Tidal-Wave** [comment]
I don't get why you say this. The slider is obviously responsive in all the provided examples. I need you to be more specific.

**Comment by kellykarnetsky** [comment]
I will create a code sample and link it as soon as I can.

**Comment by Tidal-Wave** [comment]
Thank you. I have tested several examples and have not seen an instance where the slider doesn't scale in a particular direction, and the link to the issue posted in #611 doesn't actually use bxslider anymore.

**Pull request closed without merging**
